spring.application.name=authservice

spring.datasource.url = jdbc:postgresql://localhost:5432/ecommerce
spring.datasource.username=ecommerce_user
spring.datasource.password=password123
spring.datasource.drive-class-name= org.postgresql.Driver

##JPA / HIBERNATE
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql = true
#spring.jpa.properties.hibernate.format_sql = true

##Postgresql Dialect
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect


#logging.level.org.springframework.security=DEBUG

#Oauth2.0 properties
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}


