spring.application.name=cart-service

# Active profile
spring.profiles.active=prod

# Common JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# Security
spring.security.user.name=disabled
spring.security.user.password=disabled